services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gym_application
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  db_1:
    driver: local
# Enter DB with psql -U postgres
