version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gym_tracker
    ports:
      - "5432:5432"
    volumes:
      - db_1:/var/lib/postgresql/data
volumes:
  db_1:
    driver: local
# Enter DB with psql postgres://admin:password@localhost:5432/gym_tracker
