services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    env_file:
      - ./.env
    volumes:
      - data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080

volumes:
  data:
    driver: local
# Enter DB with psql -U postgres
